### ISSUE TITLE
Add support for giv-economy-notification for zkevm cardona and zkevm mainnet

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/giveconomy-notification-service#23]

**Comment by mohammadranjbarz** [comment]
https://github.com/Giveth/giveconomy-notification-service/blob/staging/monitorConfig

**Comment by laurenluz** [comment]
thanks for creating this @mohammadranjbarz !!

**Comment by laurenluz** [comment]
@mohammadranjbarz I think this is a blocker so far before being ready right? or are we ready to test GIVeconomy notifications for zkEVM yet?

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz I think this is a blocker so far before being ready right? or are we ready to test GIVeconomy notifications for zkEVM yet?

@laurenluz I just merged to staging right now.
@maryjaf can you test it?(I don't know what is the test scenario)

**Comment by maryjaf** [comment]
the notification related to a certain network is unlock notification, am I right? @mohammadranjbarz 
I can test this notification on 3 Sep

**Comment by mohammadranjbarz** [comment]
> the notification related to a certain network is unlock notification, am I right? @mohammadranjbarz I can test this notification on 3 Sep

Cool !!
